--- #YAML:1.0
name:                POE-XS-Queue-Array
version:             0.004
abstract:            XS version of POE::Queue::Array
license:             perl
author:              
    - Tony Cook <tonyc@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    POE:                           0.29
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
